### ISSUE TITLE
Slack/GitLab App

### ISSUE THREAD

**Issue by nprail** [Filiosoft/gitlab-issue-bot#2]
The currently setup of GitLab Issue Bot (GLIB) requires each user to run their own instance of it. 

But setup can be easier! If we make GLIB a hosted GitLab and Slack app, we can make distribution and setup a simple and easy process. Users wouldn't have to run their own instance. 

### Proposed Setup Flow
1. A user clicks `Setup`on the GLIB website. 
2. GLIB redirects them to GitLab to login and give API access. 
3. After logging in with GitLab, the user is redirected to a page to install the Slack app.
4. The user signs into Slack and adds the bot user. 
5. The user goes to Slack and starts using GLIB!

The only thing that this setup doesn't cover is self hosted GitLab instances. That's a little more complex. 

### To-Do
- [ ] Build Web App - #3
- [ ] Integrate with GitLab - #3
- [ ] Integrate with Slack - #4 

### Links / Ref
- [GitLab Apps](https://docs.gitlab.com/ee/api/oauth2.html)
- [Slack Node.js SDK](http://slackapi.github.io/node-slack-sdk/)
- [Slack App Docs](https://api.slack.com/slack-apps)
